

DATA_SCAN = 100
USR_CSV_PATH = "/root/ctr_files/usr_csv/",


# 用户输入的配置
USER_START_TIME = "NOW()"
USER_TIME_RANGE = 172800
ARTICLE_START_TIME = "NOW()"
ARTICLE_TIME_RANGE = 172800
CTR_ANALYSIS_INTERVAL = 3
CTR_ANALYSIS_TOP = 12
CITE_ID = [1,2,3,4]
CITE_NAME = ["一点资讯","唔哩头条","盖饭娱乐","东方头条"]